# Pull Request Labeler configuration
# https://github.com/actions/labeler

type:bug:
  - changed-files:
      - any-glob-to-any-file: '**/test/**'

type:feature:
  - changed-files:
      - any-glob-to-any-file: 'src/**'

type:docs:
  - changed-files:
      - any-glob-to-any-file: ['docs/**', '*.md']

docs-only:
  - changed-files:
      - any-glob-to-any-file: ['docs/**', '*.md']

workflows-only:
  - changed-files:
      - any-glob-to-any-file: ['.github/workflows/**', '.github/actions/**']

type:refactor:
  - changed-files:
      - any-glob-to-any-file: ['src/**', 'test/**']

type:chore:
  - changed-files:
      - any-glob-to-any-file:
          [
            '.github/**',
            'scripts/**',
            'package.json',
            'package-lock.json',
            'Taskfile.yml',
            '.pre-commit-config.yaml'
          ]

area:js:
  - changed-files:
      - any-glob-to-any-file: ['**/*.js', '**/*.ts', '**/*.cjs']

marketplace:blocking:
  - changed-files:
      - any-glob-to-any-file:
          [
            '.vscodeignore',
            'package.json',
            'package-lock.json',
            'scripts/package-extension.js',
            'scripts/publish.sh',
            '.github/workflows/release.yml'
          ]
