name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels: [type:feature, feature]
  - title: '🐛 Fixes'
    labels: [type:bug, bug, regression]
  - title: '🔒 Security'
    labels: [type:security, security]
  - title: '📈 Performance'
    labels: [type:perf, perf]
  - title: '📚 Docs'
    labels: [type:docs]
  - title: '🧹 Internal'
    labels: [type:chore, type:refactor, dependencies]
version-resolver:
  major: { labels: [breaking] }
  minor: { labels: [type:feature, feature] }
  patch: { labels: [type:bug, type:perf, type:security, type:docs, type:chore] }
  default: patch
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
