name: Documentation
description: Report an issue with the documentation
title: '[Docs]: '
labels: ['type:docs', 'status:triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a documentation issue!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is wrong with the documentation?
    validations:
      required: true
