name: Auto-label

on:
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  labeler:
    if: github.repository == 'oaslananka-lab/kicad-studio'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true
