name: PR Size Label

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/size-label-action@v0.5.5
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
